### ISSUE TITLE
Observations missing from alerts

### ISSUE THREAD

**Issue by turley85** [AtlasOfLivingAustralia/alerts#281]
I've detected an issue with species detected in an alert for this list: 

https://lists.ala.org.au/speciesListItem/list/dr27419

R alerts have detected the following two occurrences of a species on that list:
https://biocache.ala.org.au/occurrences/337b82d0-40a2-4f6a-86b4-1f94ae00d8ce
https://biocache.ala.org.au/occurrences/7caed69d-fd06-4cbc-b1a3-ee4182834660

But this is not showing up in the Java alert:
<img width="1027" alt="image" src="https://github.com/user-attachments/assets/f3f5f7df-eb70-4150-8941-77056d5b34ca">

I cant' figure out why. Does anyone else have any clues?

**Comment by turley85** [comment]
Hmm... I wonder if the fq isn't working for those occurrences missed. IS there anyway we can check this?

**Comment by kylie-m** [comment]
Hi Andrew, for this first row, Nassella trichotoma, the spatial layer cl11170 is the new 2023 LGA layer that is still not yet loaded properly. I've tried a test run using cl10923 and I'm now getting at least one of the records through now, https://lists.ala.org.au/speciesListItem/list/dr28056 - will keep working on this one!

As an aside, could you quickly check the spatialObject ID numbers on the rest of this list? 
I think there could be an issue with the spatialObjects in the remaining rows - all but one. It appears spatialObject:9433231 on line two (_Solanum elaeagnifolium_) is correct, but the rest are sequential numbers (I'm guessing from excel) most don't have an associated spatialObject, and those that do appear incorrect.

**Comment by turley85** [comment]
Thanks @kylie-m, so should I update all lists to run off cl10923?

And did we ever get to the bottom of why cl11170 isn't loaded properly? Is this being remedied?

**Comment by kylie-m** [comment]
Thanks Andrew, yes cl10923 is best for now.  Now that Amanda is back, I've reach out and will work with her around loading of LGA 2023 layer.

**Comment by kylie-m** [comment]
Hi @turley85 I just had a look at the fq query column, a couple of things to note - 
1. there was a space between the `"` and `NILLUMBIK`, though that didn't seem to be the issue
2. a bit strange but I've got it working with the alternate wording that includes SHIRE or CITY, ie YARRA RANGES SHIRE and NILLUMBIK SHIRE 
- working on my test list https://lists.ala.org.au/speciesListItem/list/dr28056

So I've fixed that up in your VIC_DEECA_Weeds_list fq column and am now getting a record for  _Nassella trichotoma_ coming through in preview for records since 01/01/2024.   :)

**Comment by turley85** [comment]
I see Nassella trichotoma is now turning up.

However, we're still not getting an alert for the orginal missing observation: https://www.inaturalist.org/observations/239545092

[Update - BioSecurity alert for VIC_DEECA_Weeds_list.pdf](https://github.com/user-attachments/files/17300714/Update.-.BioSecurity.alert.for.VIC_DEECA_Weeds_list.pdf)

**Comment by kylie-m** [comment]
Hi Andrew, thanks for your patience on this one - apologies it took a little longer for me to respond after leave. 

The good news is I've managed to get that record into the alert preview now (for BioSecurity alert for TEST VIC DEECA Nassella trichotoma), by editing the fq column on the test list - there was a space between SHIRE and the last "  for NILLUMBIK SHIRE - this seems to have fixed the issue. 

Relevant links: 
- biocache record: https://biocache.ala.org.au/occurrences/337b82d0-40a2-4f6a-86b4-1f94ae00d8ce
- list: https://lists.ala.org.au/speciesListItem/list/dr28056
BioSecurity alert for TEST VIC DEECA Nassella trichotoma


That's a great point about the consistency of Shire vs City - I see the Science team have already responded in Slack about it, I'll link it here just so we have it  for future reference - https://atlaslivingaustralia.slack.com/archives/CCURT5KAA/p1729039411581939

**Comment by turley85** [comment]
Thanks @kylie-m Kylie, that all appears to be working now for me too! Thanks everyone!

**Comment by kylie-m** [comment]
That's great news @turley85! I'll close it off now
